# -*- coding: utf-8 -*-
"""voilence image blur___image_processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IGFCLQyIyXNWxz1awdsyhKpJG4ezEsz6

# Group 2 - Voilence Image detection and blurring

# 14_Anshu Bhagat
# 30_Rohan Dalvi
# 31_Shreyash Damania
# 40_Shivam Dubey

# Download the dataset
"""

!gdown --id 1f5fuqJQ2HlWocGI0olaP-fuiJu6pB-MQ

!unzip violence.zip

import os
dir_path = '/content/dataset/'

count = 0
for root_dir, cur_dir, files in os.walk(dir_path):
    count += len(files)
print('File count:', count)

# os.listdir('/content/dataset/train/safe')

"""# 1. Install Dependencies and Setup"""

import tensorflow as tf
import os

import cv2
from google.colab.patches import cv2_imshow

from google.colab import files
from IPython.display import Image, display

"""# 2. Remove dodgy images"""

import cv2
import imghdr

data_dir = '/content/dataset/train'

image_exts = ['jpeg','jpg', 'bmp', 'png']

for image_class in os.listdir(data_dir): 
    for image in os.listdir(os.path.join(data_dir, image_class)):
        image_path = os.path.join(data_dir, image_class, image)
        try: 
            img = cv2.imread(image_path)
            tip = imghdr.what(image_path)
            if tip not in image_exts: 
                print('Image not in ext list {}'.format(image_path))
                os.remove(image_path)
        except Exception as e: 
            print('Issue with image {}'.format(image_path))
            # os.remove(image_path)

"""# 3. Load Data"""

import numpy as np
from matplotlib import pyplot as plt

data = tf.keras.utils.image_dataset_from_directory('/content/dataset/train')

data_iterator = data.as_numpy_iterator()

batch = data_iterator.next()

fig, ax = plt.subplots(ncols=4, figsize=(20,20))
for idx, img in enumerate(batch[0][:4]):
    ax[idx].imshow(img.astype(int))
    ax[idx].title.set_text(batch[1][idx])

"""# 4. Scale Data"""

data = data.map(lambda x,y: (x/255, y))

data.as_numpy_iterator().next()

"""# 5. Split Data"""

train_size = int(len(data)*.7)
val_size = int(len(data)*.2)
test_size = int(len(data)*.1)

train_size

train = data.take(train_size)
val = data.skip(train_size).take(val_size)
test = data.skip(train_size+val_size).take(test_size)

"""# 6. Build Deep Learning Model"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout

model = Sequential()

model.add(Conv2D(16, (3,3), 1, activation='relu', input_shape=(256,256,3)))
model.add(MaxPooling2D())
model.add(Conv2D(32, (3,3), 1, activation='relu'))
model.add(MaxPooling2D())
model.add(Conv2D(16, (3,3), 1, activation='relu'))
model.add(MaxPooling2D())
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile('adam', loss=tf.losses.BinaryCrossentropy(), metrics=['accuracy'])

model.summary()

"""# 7. Train"""

logdir = 'logs'

tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=logdir)

hist = model.fit(train, epochs=10, validation_data=val, callbacks=[tensorboard_callback])

"""# 8. Plot Performance"""

fig = plt.figure()
plt.plot(hist.history['loss'], color='teal', label='loss')
plt.plot(hist.history['val_loss'], color='orange', label='val_loss')
fig.suptitle('Loss', fontsize=20)
plt.legend(loc="upper left")
plt.show()

fig = plt.figure()
plt.plot(hist.history['accuracy'], color='teal', label='accuracy')
plt.plot(hist.history['val_accuracy'], color='orange', label='val_accuracy')
fig.suptitle('Accuracy', fontsize=20)
plt.legend(loc="upper left")
plt.show()

"""# 9. Evaluate"""

from tensorflow.keras.metrics import Precision, Recall, BinaryAccuracy

pre = Precision()
re = Recall()
acc = BinaryAccuracy()

for batch in test.as_numpy_iterator(): 
    X, y = batch
    yhat = model.predict(X)
    pre.update_state(y, yhat)
    re.update_state(y, yhat)
    acc.update_state(y, yhat)

print(pre.result(), re.result(), acc.result())

"""save the model"""

import os.path
if os.path.isfile('models/anshu_model.h5') is False:
  model.save('models/anshu_model.h5')

"""load the model"""

from tensorflow.keras.models import load_model
model = load_model('models/anshu_model.h5')

"""# Predict"""

img = cv2.imread('/content/dataset/val/unsafe/734088-21afp-afp19a9ow.jpg')
plt.imshow(img)
plt.show()
# cv2_imshow(img)

resize = tf.image.resize(img, (256,256))
plt.imshow(resize.numpy().astype(int))
plt.show()

yhat = model.predict(np.expand_dims(resize/255, 0))

yhat

if yhat > 0.5: 
    print(f'Predicted class is non safe')
else:
    print(f'Predicted class is safe')

"""# Implementing the model"""

uploaded = files.upload()

uploaded = list(uploaded.keys())[0]
Image(uploaded)
img = cv2.imread(uploaded)

resize = tf.image.resize(img, (256,256))

yhat = model.predict(np.expand_dims(resize/255, 0))
print(yhat)
if yhat > 0.5:
  print("not safe image")
  blur = cv2.blur(img, (100, 100))
  cv2_imshow(blur)
else:
  print("safe") 
  cv2_imshow(img)

